// 자동 생성된 Cypher 임포트 스크립트 (온톨로지 목업)

MERGE (n:`상가` {name: '웨스트피지오짐'});
MERGE (n:`소분류업종` {name: '헬스장'});
MERGE (n:`중분류업종` {name: '스포츠 서비스'});
MERGE (n:`대분류업종` {name: '예술·스포츠'});
MERGE (n:`표준산업분류` {name: '체력 단련시설 운영업'});
MERGE (n:`행정동` {name: '마북동'});
MERGE (n:`시군구` {name: '용인시 기흥구'});
MERGE (n:`시도` {name: '경기도'});
MERGE (n:`상가` {name: '이리카츠'});
MERGE (n:`소분류업종` {name: '돼지고기 구이/찜'});
MERGE (n:`중분류업종` {name: '한식'});
MERGE (n:`대분류업종` {name: '음식'});
MERGE (n:`표준산업분류` {name: '한식 육류 요리 전문점'});
MERGE (n:`행정동` {name: '온양읍'});
MERGE (n:`시군구` {name: '울주군'});
MERGE (n:`시도` {name: '울산광역시'});
MERGE (n:`상가` {name: '투사랑해사랑해노래연습장'});
MERGE (n:`소분류업종` {name: '노래방'});
MERGE (n:`중분류업종` {name: '유원지·오락'});
MERGE (n:`표준산업분류` {name: '노래 연습장 운영업'});
MERGE (n:`행정동` {name: '상대동'});
MERGE (n:`시군구` {name: '포항시 남구'});
MERGE (n:`시도` {name: '경상북도'});
MERGE (n:`상가` {name: '건축사사무소오삼일비'});
MERGE (n:`소분류업종` {name: '건축 설계 및 관련 서비스업'});
MERGE (n:`중분류업종` {name: '기술 서비스'});
MERGE (n:`대분류업종` {name: '과학·기술'});
MERGE (n:`행정동` {name: '장안1동'});
MERGE (n:`시군구` {name: '동대문구'});
MERGE (n:`시도` {name: '서울특별시'});
MERGE (n:`건물` {name: 'J아파트'});
MERGE (n:`상가` {name: '현동노래방'});
MERGE (n:`소분류업종` {name: '일반 유흥 주점'});
MERGE (n:`중분류업종` {name: '주점'});
MERGE (n:`표준산업분류` {name: '일반 유흥 주점업'});
MERGE (n:`행정동` {name: '현동'});
MERGE (n:`시군구` {name: '창원시 마산합포구'});
MERGE (n:`시도` {name: '경상남도'});
MERGE (n:`상가` {name: '청도감이야기'});
MERGE (n:`소분류업종` {name: '백반/한정식'});
MERGE (n:`표준산업분류` {name: '한식 일반 음식점업'});
MERGE (n:`행정동` {name: '운문면'});
MERGE (n:`시군구` {name: '청도군'});
MERGE (n:`상가` {name: '부자부동산중개법인'});
MERGE (n:`소분류업종` {name: '부동산 중개/대리업'});
MERGE (n:`중분류업종` {name: '부동산 서비스'});
MERGE (n:`대분류업종` {name: '부동산'});
MERGE (n:`표준산업분류` {name: '부동산 중개 및 대리업'});
MERGE (n:`행정동` {name: '중앙동'});
MERGE (n:`시군구` {name: '창원시 성산구'});
MERGE (n:`건물` {name: '올림피아상가'});
MERGE (n:`상가` {name: '티오엠'});
MERGE (n:`소분류업종` {name: '광고 대행업'});
MERGE (n:`중분류업종` {name: '광고'});
MERGE (n:`행정동` {name: '백운면'});
MERGE (n:`시군구` {name: '제천시'});
MERGE (n:`시도` {name: '충청북도'});
MERGE (n:`상가` {name: '원디엑스'});
MERGE (n:`소분류업종` {name: '환경 관련 엔지니어링 서비스업'});
MERGE (n:`행정동` {name: '여의동'});
MERGE (n:`시군구` {name: '전주시 덕진구'});
MERGE (n:`시도` {name: '전북특별자치도'});
MERGE (n:`건물` {name: '스페이스온지식산업센터'});
MERGE (n:`상가` {name: '수담수학교습소'});
MERGE (n:`소분류업종` {name: '입시·교과학원'});
MERGE (n:`중분류업종` {name: '일반 교육'});
MERGE (n:`대분류업종` {name: '교육'});
MERGE (n:`표준산업분류` {name: '일반 교과학원'});
MERGE (n:`행정동` {name: '고덕2동'});
MERGE (n:`시군구` {name: '강동구'});
MERGE (n:`건물` {name: '고덕그라시움아파트'});
MERGE (n:`상가` {name: '더춘장'});
MERGE (n:`소분류업종` {name: '중국집'});
MERGE (n:`중분류업종` {name: '중식'});
MERGE (n:`표준산업분류` {name: '중식 음식점업'});
MERGE (n:`행정동` {name: '안양1동'});
MERGE (n:`시군구` {name: '안양시 만안구'});
MERGE (n:`상가` {name: '맨투맨학원'});
MERGE (n:`행정동` {name: '송산3동'});
MERGE (n:`시군구` {name: '의정부시'});
MERGE (n:`건물` {name: '폴리프라자'});
MERGE (n:`상가` {name: '기와집'});
MERGE (n:`소분류업종` {name: '펜션'});
MERGE (n:`중분류업종` {name: '일반 숙박'});
MERGE (n:`대분류업종` {name: '숙박'});
MERGE (n:`표준산업분류` {name: '민박업'});
MERGE (n:`행정동` {name: '서종면'});
MERGE (n:`시군구` {name: '양평군'});
MERGE (n:`상가` {name: '제이피누수'});
MERGE (n:`소분류업종` {name: '광고물 설계/제작업'});
MERGE (n:`표준산업분류` {name: '광고물 문안; 도안; 설계 등 작성업'});
MERGE (n:`행정동` {name: '보정동'});
MERGE (n:`건물` {name: '휴먼타워'});
MERGE (n:`상가` {name: '롯데1번지부동산공인중개사사무소'});
MERGE (n:`행정동` {name: '사직3동'});
MERGE (n:`시군구` {name: '동래구'});
MERGE (n:`시도` {name: '부산광역시'});
MERGE (n:`상가` {name: '정시파이터수학교습소'});
MERGE (n:`행정동` {name: '목5동'});
MERGE (n:`시군구` {name: '양천구'});
MERGE (n:`건물` {name: '현대월드타워'});
MERGE (n:`상가` {name: '복음내과의원'});
MERGE (n:`소분류업종` {name: '내과/소아과 의원'});
MERGE (n:`중분류업종` {name: '의원'});
MERGE (n:`대분류업종` {name: '보건의료'});
MERGE (n:`표준산업분류` {name: '일반의원'});
MERGE (n:`행정동` {name: '봉선2동'});
MERGE (n:`시군구` {name: '남구'});
MERGE (n:`시도` {name: '전남광주통합특별시'});
MERGE (n:`상가` {name: '지고트'});
MERGE (n:`소분류업종` {name: '여성 의류 소매업'});
MERGE (n:`중분류업종` {name: '섬유·의복·신발 소매'});
MERGE (n:`대분류업종` {name: '소매'});
MERGE (n:`표준산업분류` {name: '여자용 겉옷 소매업'});
MERGE (n:`행정동` {name: '광희동'});
MERGE (n:`시군구` {name: '중구'});
MERGE (n:`건물` {name: '지고트현대시티타워'});
MERGE (n:`상가` {name: '슬림점핑다이어트'});
MERGE (n:`소분류업종` {name: '건강보조식품 소매업'});
MERGE (n:`중분류업종` {name: '식료품 소매'});
MERGE (n:`표준산업분류` {name: '건강 보조식품 소매업'});
MERGE (n:`행정동` {name: '유천동'});
MERGE (n:`시군구` {name: '달서구'});
MERGE (n:`시도` {name: '대구광역시'});
MERGE (n:`상가` {name: '구구열쇠'});
MERGE (n:`소분류업종` {name: '철물/공구 소매업'});
MERGE (n:`중분류업종` {name: '철물·건설자재 소매'});
MERGE (n:`표준산업분류` {name: '철물 및 난방용구 소매업'});
MERGE (n:`행정동` {name: '형곡2동'});
MERGE (n:`시군구` {name: '구미시'});
MERGE (n:`상가` {name: '시원뷰티'});
MERGE (n:`소분류업종` {name: '피부 관리실'});
MERGE (n:`중분류업종` {name: '이용·미용'});
MERGE (n:`대분류업종` {name: '수리·개인'});
MERGE (n:`표준산업분류` {name: '피부 미용업'});
MERGE (n:`행정동` {name: '삼산2동'});
MERGE (n:`시군구` {name: '부평구'});
MERGE (n:`시도` {name: '인천광역시'});
MERGE (n:`건물` {name: '삼산동이리옴프라자'});
MERGE (n:`상가` {name: '치킨신드롬'});
MERGE (n:`소분류업종` {name: '치킨'});
MERGE (n:`중분류업종` {name: '기타 간이'});
MERGE (n:`표준산업분류` {name: '치킨 전문점'});
MERGE (n:`행정동` {name: '음성읍'});
MERGE (n:`시군구` {name: '음성군'});
MERGE (n:`상가` {name: '다모아'});
MERGE (n:`소분류업종` {name: '복권 발행/판매업'});
MERGE (n:`표준산업분류` {name: '복권 발행 및 판매업'});
MERGE (n:`행정동` {name: '구로5동'});
MERGE (n:`시군구` {name: '구로구'});
MERGE (n:`상가` {name: '향림한약국'});
MERGE (n:`소분류업종` {name: '약국'});
MERGE (n:`중분류업종` {name: '의약·화장품 소매'});
MERGE (n:`표준산업분류` {name: '의약품 및 의료용품 소매업'});
MERGE (n:`행정동` {name: '반송동'});
MERGE (n:`상가` {name: '촌랩'});
MERGE (n:`소분류업종` {name: '청소년 수련시설'});
MERGE (n:`중분류업종` {name: '기타 교육'});
MERGE (n:`표준산업분류` {name: '청소년 수련시설 운영업'});
MERGE (n:`행정동` {name: '퇴촌면'});
MERGE (n:`시군구` {name: '광주시'});
MERGE (n:`상가` {name: '대성환경개발'});
MERGE (n:`소분류업종` {name: '건축물 일반 청소업'});
MERGE (n:`중분류업종` {name: '청소·방제'});
MERGE (n:`대분류업종` {name: '시설관리·임대'});
MERGE (n:`행정동` {name: '조원1동'});
MERGE (n:`시군구` {name: '수원시 장안구'});
MERGE (n:`상가` {name: '롯데리아범어'});
MERGE (n:`소분류업종` {name: '버거'});
MERGE (n:`행정동` {name: '범어1동'});
MERGE (n:`시군구` {name: '수성구'});
MERGE (n:`건물` {name: '궁전맨션'});
MERGE (n:`상가` {name: '아워홈LG디스플레이기숙사점주'});
MERGE (n:`소분류업종` {name: '구내식당'});
MERGE (n:`중분류업종` {name: '구내식당·뷔페'});
MERGE (n:`표준산업분류` {name: '기관 구내식당업'});
MERGE (n:`행정동` {name: '월롱면'});
MERGE (n:`시군구` {name: '파주시'});
MERGE (n:`상가` {name: '지투모터스'});
MERGE (n:`소분류업종` {name: '자동차 세차장'});
MERGE (n:`중분류업종` {name: '자동차 수리·세차'});
MERGE (n:`표준산업분류` {name: '자동차 세차업'});
MERGE (n:`행정동` {name: '광명5동'});
MERGE (n:`시군구` {name: '광명시'});
MERGE (n:`상가` {name: '영계치킨'});
MERGE (n:`행정동` {name: '상남면'});
MERGE (n:`시군구` {name: '밀양시'});
MERGE (n:`건물` {name: '밀양예림대동타운'});
MERGE (n:`상권` {name: '성수동 카페거리'});
MERGE (n:`행정동` {name: '성수동1가'});
MERGE (n:`시군구` {name: '성동구'});
MERGE (n:`상가/브랜드` {name: '스페셜티 커피 브랜드 1호점'});
MERGE (n:`기관` {name: '서울시 도시공간본부'});
MERGE (n:`정책/계획` {name: '지구단위계획'});
MERGE (n:`도로` {name: '연무장길'});
MERGE (n:`통계수치` {name: '일평균 유동인구 9만 명 이상'});

MATCH (a {name: '웨스트피지오짐'}), (b {name: '헬스장'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '헬스장'}), (b {name: '스포츠 서비스'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '스포츠 서비스'}), (b {name: '예술·스포츠'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '웨스트피지오짐'}), (b {name: '체력 단련시설 운영업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '웨스트피지오짐'}), (b {name: '마북동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '마북동'}), (b {name: '용인시 기흥구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '용인시 기흥구'}), (b {name: '경기도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '이리카츠'}), (b {name: '돼지고기 구이/찜'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '돼지고기 구이/찜'}), (b {name: '한식'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '한식'}), (b {name: '음식'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '이리카츠'}), (b {name: '한식 육류 요리 전문점'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '이리카츠'}), (b {name: '온양읍'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '온양읍'}), (b {name: '울주군'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '울주군'}), (b {name: '울산광역시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '이리카츠'}), (b {name: '이리카츠'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '투사랑해사랑해노래연습장'}), (b {name: '노래방'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '노래방'}), (b {name: '유원지·오락'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '유원지·오락'}), (b {name: '예술·스포츠'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '투사랑해사랑해노래연습장'}), (b {name: '노래 연습장 운영업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '투사랑해사랑해노래연습장'}), (b {name: '상대동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '상대동'}), (b {name: '포항시 남구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '포항시 남구'}), (b {name: '경상북도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '건축사사무소오삼일비'}), (b {name: '건축 설계 및 관련 서비스업'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '건축 설계 및 관련 서비스업'}), (b {name: '기술 서비스'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '기술 서비스'}), (b {name: '과학·기술'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '건축사사무소오삼일비'}), (b {name: '건축 설계 및 관련 서비스업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '건축사사무소오삼일비'}), (b {name: '장안1동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '장안1동'}), (b {name: '동대문구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '동대문구'}), (b {name: '서울특별시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '건축사사무소오삼일비'}), (b {name: 'J아파트'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '현동노래방'}), (b {name: '일반 유흥 주점'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '일반 유흥 주점'}), (b {name: '주점'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '주점'}), (b {name: '음식'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '현동노래방'}), (b {name: '일반 유흥 주점업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '현동노래방'}), (b {name: '현동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '현동'}), (b {name: '창원시 마산합포구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '창원시 마산합포구'}), (b {name: '경상남도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '청도감이야기'}), (b {name: '백반/한정식'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '백반/한정식'}), (b {name: '한식'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '한식'}), (b {name: '음식'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '청도감이야기'}), (b {name: '한식 일반 음식점업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '청도감이야기'}), (b {name: '운문면'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '운문면'}), (b {name: '청도군'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '청도군'}), (b {name: '경상북도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '부자부동산중개법인'}), (b {name: '부동산 중개/대리업'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '부동산 중개/대리업'}), (b {name: '부동산 서비스'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '부동산 서비스'}), (b {name: '부동산'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '부자부동산중개법인'}), (b {name: '부동산 중개 및 대리업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '부자부동산중개법인'}), (b {name: '중앙동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '중앙동'}), (b {name: '창원시 성산구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '창원시 성산구'}), (b {name: '경상남도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '부자부동산중개법인'}), (b {name: '올림피아상가'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '티오엠'}), (b {name: '광고 대행업'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '광고 대행업'}), (b {name: '광고'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '광고'}), (b {name: '과학·기술'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '티오엠'}), (b {name: '광고 대행업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '티오엠'}), (b {name: '백운면'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '백운면'}), (b {name: '제천시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '제천시'}), (b {name: '충청북도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '원디엑스'}), (b {name: '환경 관련 엔지니어링 서비스업'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '환경 관련 엔지니어링 서비스업'}), (b {name: '기술 서비스'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '기술 서비스'}), (b {name: '과학·기술'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '원디엑스'}), (b {name: '환경 관련 엔지니어링 서비스업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '원디엑스'}), (b {name: '여의동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '여의동'}), (b {name: '전주시 덕진구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '전주시 덕진구'}), (b {name: '전북특별자치도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '원디엑스'}), (b {name: '스페이스온지식산업센터'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '수담수학교습소'}), (b {name: '입시·교과학원'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '입시·교과학원'}), (b {name: '일반 교육'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '일반 교육'}), (b {name: '교육'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '수담수학교습소'}), (b {name: '일반 교과학원'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '수담수학교습소'}), (b {name: '고덕2동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '고덕2동'}), (b {name: '강동구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '강동구'}), (b {name: '서울특별시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '수담수학교습소'}), (b {name: '고덕그라시움아파트'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '더춘장'}), (b {name: '중국집'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '중국집'}), (b {name: '중식'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '중식'}), (b {name: '음식'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '더춘장'}), (b {name: '중식 음식점업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '더춘장'}), (b {name: '안양1동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '안양1동'}), (b {name: '안양시 만안구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '안양시 만안구'}), (b {name: '경기도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '맨투맨학원'}), (b {name: '입시·교과학원'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '입시·교과학원'}), (b {name: '일반 교육'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '일반 교육'}), (b {name: '교육'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '맨투맨학원'}), (b {name: '일반 교과학원'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '맨투맨학원'}), (b {name: '송산3동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '송산3동'}), (b {name: '의정부시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '의정부시'}), (b {name: '경기도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '맨투맨학원'}), (b {name: '폴리프라자'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '기와집'}), (b {name: '펜션'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '펜션'}), (b {name: '일반 숙박'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '일반 숙박'}), (b {name: '숙박'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '기와집'}), (b {name: '민박업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '기와집'}), (b {name: '서종면'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '서종면'}), (b {name: '양평군'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '양평군'}), (b {name: '경기도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '제이피누수'}), (b {name: '광고물 설계/제작업'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '광고물 설계/제작업'}), (b {name: '광고'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '광고'}), (b {name: '과학·기술'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '제이피누수'}), (b {name: '광고물 문안; 도안; 설계 등 작성업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '제이피누수'}), (b {name: '보정동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '보정동'}), (b {name: '용인시 기흥구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '용인시 기흥구'}), (b {name: '경기도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '제이피누수'}), (b {name: '휴먼타워'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '롯데1번지부동산공인중개사사무소'}), (b {name: '부동산 중개/대리업'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '부동산 중개/대리업'}), (b {name: '부동산 서비스'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '부동산 서비스'}), (b {name: '부동산'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '롯데1번지부동산공인중개사사무소'}), (b {name: '부동산 중개 및 대리업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '롯데1번지부동산공인중개사사무소'}), (b {name: '사직3동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '사직3동'}), (b {name: '동래구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '동래구'}), (b {name: '부산광역시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '정시파이터수학교습소'}), (b {name: '입시·교과학원'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '입시·교과학원'}), (b {name: '일반 교육'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '일반 교육'}), (b {name: '교육'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '정시파이터수학교습소'}), (b {name: '일반 교과학원'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '정시파이터수학교습소'}), (b {name: '목5동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '목5동'}), (b {name: '양천구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '양천구'}), (b {name: '서울특별시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '정시파이터수학교습소'}), (b {name: '현대월드타워'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '복음내과의원'}), (b {name: '내과/소아과 의원'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '내과/소아과 의원'}), (b {name: '의원'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '의원'}), (b {name: '보건의료'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '복음내과의원'}), (b {name: '일반의원'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '복음내과의원'}), (b {name: '봉선2동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '봉선2동'}), (b {name: '남구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '남구'}), (b {name: '전남광주통합특별시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '지고트'}), (b {name: '여성 의류 소매업'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '여성 의류 소매업'}), (b {name: '섬유·의복·신발 소매'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '섬유·의복·신발 소매'}), (b {name: '소매'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '지고트'}), (b {name: '여자용 겉옷 소매업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '지고트'}), (b {name: '광희동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '광희동'}), (b {name: '중구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '중구'}), (b {name: '서울특별시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '지고트'}), (b {name: '지고트현대시티타워'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '슬림점핑다이어트'}), (b {name: '건강보조식품 소매업'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '건강보조식품 소매업'}), (b {name: '식료품 소매'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '식료품 소매'}), (b {name: '소매'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '슬림점핑다이어트'}), (b {name: '건강 보조식품 소매업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '슬림점핑다이어트'}), (b {name: '유천동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '유천동'}), (b {name: '달서구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '달서구'}), (b {name: '대구광역시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '구구열쇠'}), (b {name: '철물/공구 소매업'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '철물/공구 소매업'}), (b {name: '철물·건설자재 소매'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '철물·건설자재 소매'}), (b {name: '소매'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '구구열쇠'}), (b {name: '철물 및 난방용구 소매업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '구구열쇠'}), (b {name: '형곡2동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '형곡2동'}), (b {name: '구미시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '구미시'}), (b {name: '경상북도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '시원뷰티'}), (b {name: '피부 관리실'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '피부 관리실'}), (b {name: '이용·미용'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '이용·미용'}), (b {name: '수리·개인'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '시원뷰티'}), (b {name: '피부 미용업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '시원뷰티'}), (b {name: '삼산2동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '삼산2동'}), (b {name: '부평구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '부평구'}), (b {name: '인천광역시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '시원뷰티'}), (b {name: '삼산동이리옴프라자'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '치킨신드롬'}), (b {name: '치킨'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '치킨'}), (b {name: '기타 간이'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '기타 간이'}), (b {name: '음식'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '치킨신드롬'}), (b {name: '치킨 전문점'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '치킨신드롬'}), (b {name: '음성읍'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '음성읍'}), (b {name: '음성군'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '음성군'}), (b {name: '충청북도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '다모아'}), (b {name: '복권 발행/판매업'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '복권 발행/판매업'}), (b {name: '유원지·오락'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '유원지·오락'}), (b {name: '예술·스포츠'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '다모아'}), (b {name: '복권 발행 및 판매업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '다모아'}), (b {name: '구로5동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '구로5동'}), (b {name: '구로구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '구로구'}), (b {name: '서울특별시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '향림한약국'}), (b {name: '약국'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '약국'}), (b {name: '의약·화장품 소매'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '의약·화장품 소매'}), (b {name: '소매'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '향림한약국'}), (b {name: '의약품 및 의료용품 소매업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '향림한약국'}), (b {name: '반송동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '반송동'}), (b {name: '창원시 성산구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '창원시 성산구'}), (b {name: '경상남도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '촌랩'}), (b {name: '청소년 수련시설'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '청소년 수련시설'}), (b {name: '기타 교육'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '기타 교육'}), (b {name: '교육'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '촌랩'}), (b {name: '청소년 수련시설 운영업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '촌랩'}), (b {name: '퇴촌면'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '퇴촌면'}), (b {name: '광주시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '광주시'}), (b {name: '경기도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '대성환경개발'}), (b {name: '건축물 일반 청소업'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '건축물 일반 청소업'}), (b {name: '청소·방제'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '청소·방제'}), (b {name: '시설관리·임대'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '대성환경개발'}), (b {name: '건축물 일반 청소업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '대성환경개발'}), (b {name: '조원1동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '조원1동'}), (b {name: '수원시 장안구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '수원시 장안구'}), (b {name: '경기도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '롯데리아범어'}), (b {name: '버거'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '버거'}), (b {name: '기타 간이'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '기타 간이'}), (b {name: '음식'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '롯데리아범어'}), (b {name: '범어1동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '범어1동'}), (b {name: '수성구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '수성구'}), (b {name: '대구광역시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '롯데리아범어'}), (b {name: '궁전맨션'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '아워홈LG디스플레이기숙사점주'}), (b {name: '구내식당'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '구내식당'}), (b {name: '구내식당·뷔페'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '구내식당·뷔페'}), (b {name: '음식'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '아워홈LG디스플레이기숙사점주'}), (b {name: '기관 구내식당업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '아워홈LG디스플레이기숙사점주'}), (b {name: '월롱면'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '월롱면'}), (b {name: '파주시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '파주시'}), (b {name: '경기도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '지투모터스'}), (b {name: '자동차 세차장'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '자동차 세차장'}), (b {name: '자동차 수리·세차'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '자동차 수리·세차'}), (b {name: '수리·개인'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '지투모터스'}), (b {name: '자동차 세차업'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '지투모터스'}), (b {name: '광명5동'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '광명5동'}), (b {name: '광명시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '광명시'}), (b {name: '경기도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '영계치킨'}), (b {name: '치킨'}) MERGE (a)-[:`속한업종` {confidence: 0.95}]->(b);
MATCH (a {name: '치킨'}), (b {name: '기타 간이'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '기타 간이'}), (b {name: '음식'}) MERGE (a)-[:`상위분류` {confidence: 0.95}]->(b);
MATCH (a {name: '영계치킨'}), (b {name: '치킨 전문점'}) MERGE (a)-[:`표준산업분류매핑` {confidence: 0.8}]->(b);
MATCH (a {name: '영계치킨'}), (b {name: '상남면'}) MERGE (a)-[:`위치` {confidence: 0.9}]->(b);
MATCH (a {name: '상남면'}), (b {name: '밀양시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '밀양시'}), (b {name: '경상남도'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '영계치킨'}), (b {name: '밀양예림대동타운'}) MERGE (a)-[:`소재` {confidence: 0.85}]->(b);
MATCH (a {name: '성수동 카페거리'}), (b {name: '성수동1가'}) MERGE (a)-[:`위치` {confidence: 0.85}]->(b);
MATCH (a {name: '성수동1가'}), (b {name: '성동구'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '성동구'}), (b {name: '서울특별시'}) MERGE (a)-[:`소속` {confidence: 0.9}]->(b);
MATCH (a {name: '스페셜티 커피 브랜드 1호점'}), (b {name: '성수동 카페거리'}) MERGE (a)-[:`위치` {confidence: 0.4}]->(b);
MATCH (a {name: '서울시 도시공간본부'}), (b {name: '지구단위계획'}) MERGE (a)-[:`수립` {confidence: 0.85}]->(b);
MATCH (a {name: '지구단위계획'}), (b {name: '연무장길'}) MERGE (a)-[:`대상지역` {confidence: 0.8}]->(b);
MATCH (a {name: '연무장길'}), (b {name: '성수동1가'}) MERGE (a)-[:`소속` {confidence: 0.7}]->(b);
MATCH (a {name: '성수동 카페거리'}), (b {name: '일평균 유동인구 9만 명 이상'}) MERGE (a)-[:`통계` {confidence: 0.75}]->(b);